#!/bin/bash

rfile='./Reaction/47Kdp_Sim_0000MeV.reaction'

cd ~/Programs/nptool/Projects/e793s;
cmake ./;
make -j6;
npsimulation -D ./Detector/mugast_08Nov.detector -E $rfile -B ./runsimulation.mac -O $1;

directory=' /home/charlottepaxman/Programs/nptool/Outputs/Simulation/'
dotroot='.root'
filename=$directory$1$dotroot

sim='Sim_'
outfile=$sim$1

echo "TTreeName" > RunToTreat_AutoGenerated.txt
echo " SimulatedTree" >> RunToTreat_AutoGenerated.txt
echo "RootFileName" >> RunToTreat_AutoGenerated.txt
echo $filename >> RunToTreat_AutoGenerated.txt

npanalysis -R RunToTreat_AutoGenerated.txt -E $rfile -D Detector/mugast_08Nov.detector -C Calibration.txt -O $outfile;
