#!/bin/bash

rm RunToTreat_AutoGenerated.txt

#====================================================
#rfile='./Reaction/47Kdp_11Jul22_Sim0p000.reaction'
#rfile='./Reaction/47Kdp_11Jul22_Sim1p981.reaction'
#rfile='./Reaction/47Kdp_11Jul22_Sim4p045.reaction'
#rfile='./Reaction/47Kdp_11Jul22_Sim4p393.reaction'
#------
#rfile='./Reaction/47Kdd_11Jul22.reaction'
#rfile='./Reaction/47Kdd_11Jul22_Sim.reaction'
#------
#rfile='./Reaction/47Kpp_11Jul22.reaction'
#----------------------------------------------------
#rfile='./Reaction/47Kdp_18Oct22.reaction'
rfile='./Reaction/47Kdt_18Oct22.reaction'
#====================================================
#====================================================
#dfile='Detector/mugast_08Nov.detector'
#----------------------------------------------------
#dfile='Detector/mugast_11Jul22.detector'
#dfile='Detector/mugast_testingMG1dip.detector'
#----------------------------------------------------
#dfile='Detector/mugast_01Sep22.detector'
#----------------------------------------------------
dfile='Detector/mugast_18Oct22.detector'
#dfile='Detector/mugast_18Oct22_Tx2.detector'
#dfile='Detector/mugast_18Oct22_Tx0p5.detector'
#====================================================

cd ~/Programs/nptool/Projects/e793s;
cmake ./;
make -j6;

directory='/home/charlottepaxman/Programs/nptool/Outputs/Simulation/'
dotroot='.root'
dash='-'

for x in 1 #2 3 4 5 6 7 8 9 10
do
        outname=$1$dash$x
	#npsimulation -D $dfile -E $rfile -B ./runsimulation.mac -O $outname;
	npsimulation -D $dfile -E $rfile -B ./runsimulation_small.mac -O $outname;
	filename=$directory$1$dash$x$dotroot
done

space=" "
sim='Sim_'
outfile=$sim$1

echo "TTreeName" >> RunToTreat_AutoGenerated.txt
echo " SimulatedTree" >> RunToTreat_AutoGenerated.txt
echo "RootFileName" >> RunToTreat_AutoGenerated.txt

for x in 1 #2 3 4 5 6 7 8 9 10
do
	echo "$space""$directory""$1""$dash""$x""$dotroot" >> RunToTreat_AutoGenerated.txt
done

npanalysis --definition Sim -R RunToTreat_AutoGenerated.txt -E $rfile -D $dfile -O $outfile;
#npanalysis --definition Sim --definition ExcludeThePoor -R RunToTreat_AutoGenerated.txt -E $rfile -D $dfile -O $outfile;


